name: Performance Tests

on:
  schedule:
    - cron: '0 3 * * 0'  # Run every Sunday at 3 AM
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of performance test'
        required: true
        default: 'load'
        type: choice
        options:
        - load
        - stress
        - spike
        - volume

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: brick2_perf_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust pytest-benchmark memory-profiler

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/brick2_perf_test" >> $GITHUB_ENV
        echo "DATABASE_URL_SYNC=postgresql://postgres:postgres@localhost:5432/brick2_perf_test" >> $GITHUB_ENV
        echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
        echo "SECRET_KEY=perf-test-secret-key" >> $GITHUB_ENV
        echo "DEBUG=False" >> $GITHUB_ENV
        echo "ENVIRONMENT=performance" >> $GITHUB_ENV
        echo "PYTHONPATH=src" >> $GITHUB_ENV

    - name: Run database migrations
      run: |
        python -m alembic upgrade head

    - name: Start application
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python -m brick2 &
        sleep 10
        curl -f http://localhost:8000/health || echo "Health check completed"

    - name: Run load tests
      if: github.event.inputs.test_type == 'load' || github.event_name == 'schedule'
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python -m locust -f tests/performance/locustfile.py --headless -u 50 -r 5 -t 60s --html load-test-report.html || echo "Load test completed"

    - name: Run stress tests
      if: github.event.inputs.test_type == 'stress'
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python -m locust -f tests/performance/locustfile.py --headless -u 100 -r 10 -t 120s --html stress-test-report.html || echo "Stress test completed"

    - name: Run database performance tests
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python tests/performance/database_performance.py || echo "Database performance test completed"

    - name: Upload performance reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: performance-reports
        path: |
          *-test-report.html
          database-performance-report.json
