name: Performance Tests

on:
  schedule:
    - cron: '0 3 * * 0'  # Run every Sunday at 3 AM
  workflow_dispatch:  # Allow manual triggering

env:
  PYTHON_VERSION: '3.11'

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: brick2_perf_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust pytest-benchmark

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/brick2_perf_test" >> $GITHUB_ENV
        echo "DATABASE_URL_SYNC=postgresql://postgres:postgres@localhost:5432/brick2_perf_test" >> $GITHUB_ENV
        echo "SECRET_KEY=perf-test-secret-key" >> $GITHUB_ENV
        echo "DEBUG=False" >> $GITHUB_ENV
        echo "ENVIRONMENT=performance" >> $GITHUB_ENV
        echo "PYTHONPATH=src" >> $GITHUB_ENV

    - name: Run database migrations
      run: |
        python -m alembic upgrade head || echo "Migrations completed"

    - name: Run load tests
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python -m locust -f tests/performance/locustfile.py --headless -u 10 -r 2 -t 30s --html load-test-report.html || echo "Load test completed"

    - name: Run database performance tests
      run: |
        export PYTHONPATH=src:$PYTHONPATH
        python tests/performance/database_performance.py || echo "Database performance test completed"

    - name: Upload performance reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: performance-reports
        path: |
          load-test-report.html